### ISSUE TITLE
3D rendering features road map

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#354]
Planned Features -

- [ ] Naty Hoffman-style LUT color grading support (https://youtu.be/ISgTcDlZaLs?t=2267)
- [ ] Light adaptation via Auto-Exposure (disabled by default to not confuse new users).
- [ ] Sky Atmosphere (https://blog.maximeheckel.com/posts/on-rendering-the-sky-sunsets-and-planets/)
- [ ] Fuzz (weight, roughness) rendering. Fuzz color will simply be albedo for economy.
- [ ] Investigate the practicability of PCSS in place of PCF.
- [ ] #833 
- [ ] #1315
- [ ] #1314
- [ ] #1313
- [ ] #1312
- [ ] #1274
- [ ] #1187
- [ ] #1316
- [ ] Deferred Decals (perhaps more challenging than thought - https://github.com/FlaxEngine/FlaxEngine/issues/3080)
- [ ] #1098
- [ ] Experiment with Hashed Alpha Testing (https://research.nvidia.com/labs/rtr/publication/wyman2017hashed/)
- [ ] #935
- [ ] #811
- [ ] #700
- [ ] Procedural Foliage with some decent means of occlusion culling (might be a little too game-specific for us to sufficiently generally define) - https://www.youtube.com/watch?v=bp7REZBV4P4, https://hexaquo.at/pages/grass-rendering-series-part-3-animating-and-interacting-with-grass-in-godot/
- [ ] #998
- [ ] Small Water Body Shader (using refraction and maybe diffraction, but no planar reflection - like the water bodies in RE8).
- [ ] Large Water Body Shader (using refraction and maybe diffraction, and planar reflection).
- [ ] Per-Object Motion Blur (since we'll probably need a velocity buffer for things like FSR and DLSS at some point anyways).

Anticipated Features (not planned per se, and the engine will not necessarily have the data structuring and scaffolding to easily slide them in, but some are almost certainly necessary for someone) -

- [ ] Sheen
- [ ] Lens Flares
- [ ] Experiment with #694
- [ ] #1023 (MVEB)
- [ ] Advanced hair rendering (https://arxiv.org/pdf/2607.04230)
- [ ] Microshadowing (https://irradiance.ca/posts/microshadowing-part1/, https://irradiance.ca/posts/microshadowing-part2/)
- [ ] Anisotropy shading such as for brushed metals
- [ ] Screen-space shadows that account for height texture a la Days Gone
- [ ] Some sort of generalized rendering occlusion solution such as https://medium.com/@Umbra3D/introduction-to-occlusion-culling-3d6cfb195c79 or #518
- [ ] Vista Shadows a la Buldur's Gate 3 (https://www.youtube.com/watch?v=zuDjcoabX7U&list=PLLaly9x9rqjsXLW1tMFruyh_657sh8epk&index=10)
- [ ] Ray-traced AO as an example to get started doing Vulkan ray-tracing stuff (not that we'd likely do ray-traced AO as its own feature - https://github.com/JorenJoestar/DevGames2025)
- [ ] Baked GI (w/ specular!) - https://blog.selfshadow.com/publications/s2015-shading-course/rad/s2015_pbs_rad_slides.pdf
- [ ] Screen Space Global Illumination (https://www.youtube.com/watch?v=dmdyqzelBIY, https://github.com/JoshuaLim007/Graphics_CS/blob/main/Assets/Shaders/SSGI.frag)

Misc. Reference Materials:
https://github.com/bryanedds/Nu/wiki/Additional-Resources#educational-resources-and-references

**Comment by bryanedds** [comment]
Another vital item is the ability to import from Unity and / or Unreal. Implementing a USD import process for Nu is one possibility -

https://docs.unrealengine.com/4.26/en-US/WorkingWithContent/USDinUE4/

https://github.com/unity3d-jp/USDForUnity

**Comment by bryanedds** [comment]
Looks like there's some .NET USD bindings here -

https://github.com/unity3d-jp/USDForUnity/blob/master/USDForUnity/Assets/UTJ/USDForUnity/Scripts/usdi.cs

Along with the example code for dealing with Unity, this could be a great start!

**Comment by bryanedds** [comment]
Newer repo here -

https://github.com/Unity-Technologies/usd-unity-sdk

**Comment by bryanedds** [comment]
Mesh Distance Fields can buy several advanced rendering features - https://docs.unrealengine.com/5.0/en-US/mesh-distance-fields-in-unreal-engine/

Their expense might be worth it since I've heard they could be used in place of shadow maps. `// TODO: verify this.`

**Comment by bryanedds** [comment]
Compile all shaders in a package when hint-loaded?

**Comment by bryanedds** [comment]
How will we do mesh picking in the editor? Triangle picking?

**Comment by bryanedds** [comment]
Unfortunately, it appears that mixing SDL rendering with OGL rendering is unsupported. This means I will probably have to start by rewriting the 2d renderer in OGL.

First, I need to design the 2d renderer. I am thinking that I will have a finite number of material parameters for any 2d renderable. That way sprite sorting / batching can be a static process. Unlike 3d rendering, 2d render messages are not composed of materials, but will stay pretty much the same API. It will be implemented with painter's algorithm rather than using z testing since, due to transparencies, we have to keep the sorting algorithm anyway. Like the 3d renderer - or perhaps even moreso - there will only be one rendering model for 2d. While I may add features to the one 2d material over time, I won't provide a way for users to extend it with additional parameters. Nor am I immediately going to provide any pre or post-processing 2d API. Again, that could be added later without restructuring the API. 

This leaves a lot of power and features on the table for 2d rendering, but the fact that I have to whip this out in a week or two in order to meet my deadlines helps disambiguate that decision.

Fortunately, it does seem the sdl_ttf will work with opengl, so I won't have to figure out another way to render text - https://stackoverflow.com/questions/5289447/using-sdl-ttf-with-opengl.

**Comment by bryanedds** [comment]
Even with such a simple 2d rendering model, there's still a couple interesting things I can do basically for free (in terms of implementation cost). 2d normal maps, for example, as well as specular maps (tho that would require a light source render message). Pre and post passes actually would be basically free in terms of implementation. An Elevation buffer could also allow for some interesting effects.

Also, I need to design how the 2d and 3d images come together if 2d is going to have pre and post passes. I would need a destination alpha channel on the target 2d buffer and then render the target 2d buffer on top of the 3d buffer.

With an elevation buffer, some forms of 2d shadowing would be possible, but I dontt think general enough to implement.

**Comment by bryanedds** [comment]
While I can't necessarily allow the user to extend the 2d material interface, I could allow them to replace it and the rendering process itself with a 2d equivalent for https://github.com/bryanedds/Nu/blob/c3f908cba821f3407c574757cc78f9482df2c957/Nu/Nu/Render3d.fs#L48

**Comment by bryanedds** [comment]
Approximate render pass order -

shadow map -> occlusion -> geometry -> decals -> lighting -> screen space reflection -> tone mapping -> fsaa

**Comment by bryanedds** [comment]
For several reasons, mostly due to lack of tooling support, USD files aren't likely going to be our target scene format, but rather FBX. Unity FBX does a pretty good job. Just take the objects you want to export, put them under a single GameObject, then use `GameObject -> Export to FBX...`.

**Comment by bryanedds** [comment]
FBX export from Unity is great and all, but the immediate question is how to attach user-defined data to an object and retrieve it in Nu. I'm guessing we can build an exporter shell that calls the FBX export function as well as produces a key value file that maps from object names to a the UserProperty string field of a custom component. This is ratty and probably only useful as an internal tool, but I think it would work.

**Comment by bryanedds** [comment]
A few asset packs for testing the renderer -
https://assetstore.unity.com/packages/3d/environments/urban/atmospheric-house-modular-192712
https://assetstore.unity.com/packages/3d/environments/urban/hq-abandoned-school-modular-106665
https://assetstore.unity.com/packages/3d/environments/urban/qa-police-station-162515

**Comment by bryanedds** [comment]
For the metadata pipeline, I might allow users to specify a .meta file for each asset like Unity, but unlike Unity, .meta files are completely optional. The user-defined .meta files are then fed into the metadata pipeline process, resulting in either a single monolithic metadata output file in the bin folder or one .meta file per asset in the bin folder. The important thing is to make .meta files not being a huge PITA like in Unity.

**Comment by bryanedds** [comment]
I have so far only found one seemingly usable Physx wrapper, but it seems questionable as to how cross-platform it will be -

https://github.com/stilldesign/PhysX.Net/blob/master/PhysX.Net/PhysX.Net/Source/StdAfx.h#L25-L26

**Comment by bryanedds** [comment]
Bullet physics used instead of Physx.

UPDATE: Jolt physics used instead of Bullet physics.

**Comment by bryanedds** [comment]
We should consider shadow caching as an optimization feature.

**Comment by bryanedds** [comment]
We could also consider giving lights contact shadows if VSM makes things look too floaty.

**Comment by bryanedds** [comment]
We probably need to prioritize the following features, only one of which are on the current roadmap -
- ssr (done)
- volumetric lighting (done)
- per-light probe ambient properties (done)
- light map subsumption (done)
- dynamic / adaptive tone mapping (done)

**Comment by bryanedds** [comment]
There are .net bindings for an opengl-based fork of FSR2 -

https://github.com/BoyBaykiller/FidelityFX-FSR2-CSharpBindings/

(OpenGL-based fork of FSR2 here - tho there seem to be some unresolved performance problems...)

https://github.com/JuanDiegoMontoya/FidelityFX-FSR2-OpenGL/

**Comment by bryanedds** [comment]
Let's consider adding SSGI to the list of desirable features -

```
Screen-Space Global Illumination (SSGI) is a real-time rendering technique that approximates the indirect lighting effects of global illumination—all by working solely on the rendered image buffers (such as depth, normals, and color). In traditional global illumination, light bounces around a scene, illuminating areas that aren't directly lit by a light source. However, computing accurate light inter-reflections is computationally expensive. SSGI sidesteps this by using the information already available from the screen to simulate the effect of bounced light.

How It Works: SSGI leverages the post-processed scene data—in particular, the depth and normal buffers—to reconstruct an approximate view of the scene's geometry. Then, for each pixel, the algorithm samples nearby pixels or casts rays in screen space to evaluate the contribution of indirect lighting. If a ray encounters a surface or if nearby pixels contain bright light due to a direct or already computed indirect contribution, those effects are accumulated to approximate how much indirect light bounces onto that pixel. This helps simulate phenomena such as soft shadows, color bleeding, and ambient reflections. The technique often involves some form of raymarching or limited ray-tracing within the confines of the visible scene.

Key Characteristics and Trade-offs:

Performance: Because SSGI operates in screen space, it avoids the heavy computational cost of full global illumination algorithms. It makes clever use of existing buffers, thereby keeping the calculations relatively lightweight and suitable for real-time applications like games.

Limited to Visible Data: Since the algorithm operates on what’s rendered, it can only account for geometry and lighting information that is currently visible on the screen. This can lead to artifacts at screen edges, or when important data lies outside the current view.

Approximation: SSGI is inherently an approximation. While it can produce convincing effects and enhance the overall feeling of realism, it might not capture all details of light interactions in a fully physically accurate manner.

Integration with Deferred Rendering: It works particularly well in deferred shading pipelines, as the necessary buffers (depth, normals, albedo) are already being generated during the rendering process.

In Practice: Imagine a room with a bright lamp. Direct lighting from the lamp illuminates nearby objects sharply, but in a realistic scenario, light bounces off the walls, ceiling, and objects, subtly lighting up darker crevices. SSGI would sample the screen’s depth and color data to pick up these indirect hints, softening shadows and tinting areas with the relevant indirect light contributions—even though it’s not simulating every light bounce in full detail.
```

**Comment by bryanedds** [comment]
Order of post-processing in Unreal -

![Image](https://github.com/user-attachments/assets/82e632bb-b5f1-4c44-9df9-5bc67f1c9902)

**Comment by bryanedds** [comment]
Feature tiling is an interesting way to optimize deferred rendering -

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/4296baf2-27ea-4d97-ab51-9734911a0eb6" />

https://youtu.be/fXakIV1OFes?t=2746
